kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-nginx
  labels:
    app: deploy-nginx-label
    

spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-nginx-label
  template:
    metadata:
      labels:
        app: deploy-nginx-label
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        
       
