apiVersion: v1
kind: Service
metadata:
  name: svc-deploy-2
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: deploy-nginx-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
